Ctoic/Lisbook

index.html

Added a card design for the book.
Included hover effects and animations.
Ensured the layout is responsive.
Added a "like" or "favorite" button functionality.

Added Card and Animations

---

README.md

` Ref #11`
Added basic dynamic contributor section at bottom of readme. If section doesn't look good we can work on it later.

added dynamic contributors section at bottom of readme

---

fs.html
index.html
package-lock.json
pbd.html
rdpd.html

I've added a toggle feature to all pages, allowing users to switch between light and dark themes.

added a toggler to all the pages to toggle between light and dark theme

---

index.html

https://github.com/user-attachments/assets/e4949522-f181-407a-956c-51dc34c42535
This is what i have done for home page.

[#8] Home page mobile menu navigation added

---

app.js
index.html
style.css

I have added Play/Pause animation . Please preview it and please giver hacktoberfest tag @Ctoic

Play/Pause Animation added

---

.github/workflows/contributors.yml
README.md

Hey @Ctoic please check the functionality of dynamic add-contributors is working or not by merging this PR.
Created a workflow to add contributors dynamically.
Every time you merge the code to master, workflow will get triggered and contributors will get added to README.md.

Adding Contributors to README.md dynamically [#9]

---

index.html

- Modified the main container to use `w-full` for full-width display
- Removed margin classes to allow the div to span the entire page width
- Enhanced list item styles for better hover effects and user experience
- Added a play/pause button with consistent styling
-https://deploy-preview-25--lisbook.netlify.app/

feat: Make audio playlist div full-width

---

fs.html
index.html
pbd.html
rdpd.html
script.js
style.css

- Added dynamic background color management for `playlist-card` elements depending on theme (light or dark).
- CSS updated to support `light-theme` and `dark-theme` classes, ensuring smooth color transition when changing theme.
- Corrected theme-toggle behavior to ensure a consistent experience across the page.
- Harmonization of text and background colors in both themes.
Objective: Improve UX by ensuring that all page elements react correctly to theme changes and by harmonizing the user interface.

Improved theme management and updated interface

---

script.js

**Description:**
This PR addresses two key issues related to the error popup functionality and audio playback error handling.
**Changes Made:**
1. Popup Functionality:
- Fixed the close button for the error popup, ensuring it functions correctly by attaching the event listener immediately after the popup is created.
- The close button now effectively removes both the popup and the background overlay.
2. Audio Playback Error Handling:
- Enhanced the error handling logic for audio playback to provide more specific error messages.
- Incorporated checks for NotSupportedError to indicate unsupported audio formats or missing files, while also handling general playback issues gracefully.
3. Background Overlay:
- The overlay now includes a blur effect to improve user experience by preventing …

Enhance Audio Playback Error Handling with error popups

---

data/books.json
index.html
script.js
style.css

Added Tooltips on hover. Added action button color change on hover.

---

fs.html
index.html
pbd.html
rdpd.html

Added download button for all podcast in all files
for the issue: #33 
https://github.com/user-attachments/assets/b6dcce06-2daf-40d9-8ae5-dc65545ff128

Added Download button to all podcast

---

.github/workflows/main.yml
README.md

I first created a workflow for github actions and then added some comments to the readme file. now it will automatically get updated when more users contribute. I used this: https://github.com/akhilmhdh/contributors-readme-action
Screenshot readme:

Fixed the issue - All the contributors are not visible On readme. #53

---

adventures.html
fs.html
index.html
pbd.html
rdpd.html
test.html

Hello,
Hope you're doing well
I would like to work on issue #76 too
After making necessary changes, the twitter logo looks something like this in the html pages:
Light Mode:
Dark Mode:
Kindly go through the code changes and let me know if they seem to be fine
Sincere apologies for my mistakes if you find any
Thanks and Regards,
Mohit Kambli

Fix #76 : Update Twitter logo

---

adventures.html
fs.html
index.html
pbd.html
rdpd.html
script.js
style.css
test.html

#73 
Adding the progress bars for the audio files.
Which will show how much audio you have listened to.
If you pause in between and refresh page you can again start from the same point.
Adding the screenshots for more details

add progress bars for the audio files

---

faq.html
script.js
style.css

issue number #104 is resolved (AFTER IMAGES)

theme is stable throughout the pages #104 (Fixes for Issue #104)

---

adventures.html
app.js
fs.html
index.html
pbd.html
rdpd.html
script.js
test.html

Fixes - #108 
Description - Added button for changing the playback speed from the dropdown

Added functionality for increasing and decreasing the playback speed

---

about.html
contact.html
faq.html
index.html
script.js
style.css

#119 smooth cursor added, great addition

smooth cursor added

---

about.html
faq.html
index.html
script.js
style.css

#118 the typing effect when hovered over a question making the section more appealing.
also resolved theme related bugs

faq typing effect added

---

about.html
contact.html
faq.html
index.html
pages/footer.html
profile.html
script.js
style.css

<h1 align="center">#113 for the addition of new feature, profile section with friends list and so much more.</h1>
<h2 align="center">NEW PROFILE SECTION WITH HOURS LISTENED AND FRIENDS LIST (INTERACTIVE)</h2>
<p align="center">
</p>
<h2 align="center">IN DARK THEME</h2>
<p align="center">
</p>
<h2 align="center">NEW SUN AND MOON CHANGING ICONS FOR THE THEMES</h2>
<p align="center">
</p>
<h2 align="center">BUG FIXED, FOOTER IS NOW THEME ORIENTED</h2>
<p align="center">
</p>

new feature - profile section 

---

contact.html
script.js
style.css

#135 issue fixed 
(INTERACTIVE MAP ADDED- CONTACT US REQUIRED)
(UPDATED FORM, WITH WORKING FEATURES)

contact page updated

---

README.md
adventures.html
fs.html
pbd.html
rdpd.html
style.css
translation.js

Add Simplified Chinese as new multi-language support #37
Fix missing green circles cursors mentioned in #131 
This pull request adds new language option: Simplified Chinese, and translations for the book "Frankenstein" in both English and Chinese. The translations include the title, author and description. This pr also fix the missing green circles cursor in audiobook pages.
- Updated fs.html by adding new language option: Simplified Chinese
- Updated `translations.js` to include translations for both English and Simplified Chinese.
- Updated adventures.html, fs.html, pbd.html and rdpd.html to fix the green circles cursor issue

Add Simplified Chinese as new multi-language support and fix missing green circles cursor

---

.vscode/settings.json
adventures.html
fs.html
gd.html
index.html
pbd.html
rdpd.html
style.css

Improve language selection button attractiveness

---

about.html
contact.html
faq.html
fs.html
index.html
profile.html
scripts.js
style.css

This pull request implements the following changes:
Added Pac-Man animation in the phone frame.
Implemented dot fading effect for forward and backward movement.
Updated CSS for animation smoothness and visual improvements.
Increased dot fading duration for better visual experience.

 added loading feature according to the provided figma design

---

about.html
script.js

Closes #208
This PR  adds a contributor section in About page, which shows list of all contributors and get updated dynamically.
---
- No section to show contributors of this repo
- This section is required to celebrate our contributors and for their recognition 
---
- Add a section which shows list of contributors with their github profile card. Card display essential information about that user
- Add a link to contributor's individual github profile
---
- Project contributors get their recognition for contributing to the repo.
- Boosts Open Source project contributions.

Feat: Show contributors dynamically

---

script.js

This PR introduces a dedicated About Us page (about.html) to showcase the project's mission, philosophy, and—most importantly—to recognize the project's contributors.
The page is designed to be fully responsive and integrates seamlessly with existing application features by relying on the logic already present in script.js.
Key Changes:
Adds structure "Open Source Commitment" sections.
Uses the header-placeholder and footer-placeholder elements for file inclusion via loadHTML (from script.js).
The "Meet the Team" section uses a container class (.row.row-cols-1.row-cols-md-3.row-cols-lg-5.g-4.mt-4.align-items-  stretch) that is targeted by the loadContributors() function in script.js. This ensures the contributor cards are automatically fetched from the GitHub repository (Ctoic/Lisbook) …

Feature/About Page: Implement responsive About section with dynamic GitHub contributors #208

---

index.html

Removed that line from the main page now that problem will not occur making the website clean 
Please @Ctoic check and merge the PR and add the hactoberfest label along with the level of contribution. Let me know if require any changes.
fixes #221

bug removed

---

about.html
explore.html
faq.html
header-footer.js
index.html
pages/package-lock.json
style.css

When I ran the code , there was no footer section visible so I added one :

Added footer section

---

.vscode/settings.json
SCANNER_GUIDE.md
SCANNER_QUICK_START.md
about.html
explore.html
explore.js
explore_style.css
faq.html
fs.html
gd.html
header-footer.js
index.html
pages/package-lock.json
profile.html
scan.css
scan.html
scan.js
share.js
style.css

Closes: #243
This PR  fixes the  ui for add friend button at profile page, both in normal and expanded form  and is responsive
---
- Add friend button UI is broken
-  UI is also not good for expanded form
---
- Improve ui , ad d proper width to button
- Provide padding and width to the input searh and button
- ALign the icon with text in button
---
- Improves user experience and accessibility.

UI: add friend button ui fix

---

index.html

This PR updates the `index.html` file to address homepage rendering issues and improve overall HTML structure. The changes are intended to:
- Resolve rendering issues on the homepage.
- Fix minor HTML inconsistencies and structure-related bugs.
- Ensure smooth compatibility with revised JS files (`app.js`, `explore.js`, `share.js`).
No other files were modified in this PR.
- **`index.html`**: Updated structure and corrected minor inconsistencies.
- No changes were made to CSS or JS files in this PR.
- Homepage loads correctly without errors.
- Navigation, hero section, and top audio books section render as expected.
- All links, buttons, and modals function properly with the updated HTML.
- This PR focuses solely on HTML updates.
- JS and CSS files remain unchanged; separate PRs address …

Fix JS errors in app.js, explore.js, share.js for homepage (Issue #212)
